services:
  auth:
    build:
      context: ./auth
    container_name: auth-service
    ports:
      - "3001:3001"
    # ❌ Do not use volumes during debugging, can break node_modules
    # volumes:
    #   - ./auth:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=devforge_super_secret_key
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"